data:
  batch_size: 64
  num_workers: 4
  resize:
  - 224
  - 224
  norm_mean:
  - 0.5
  - 0.5
  - 0.5
  norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_classes: 10
checkpoint:
  dir: ./checkpoints
visualization:
  save_dir: ./figures
training:
  total_epochs: 30
  lr: 0.0001
  loss: CrossEntropyLoss
  optimizer: Adam
  seed: 42
  device: cuda:0
  patience: 10
experiment:
  experiments:
  - model: ResNet50
    model_type: resnet
    pretrained: false
  - model: ViT-S
    model_type: vit
    pretrained: false
  - model: ResNet50
    model_type: resnet
    pretrained: true
  - model: ViT-S
    model_type: vit
    pretrained: true
